export const colourOptions = [
    { value: 'ocean', label: 'ABI', color: '#00B8D9'},
    { value: 'blue', label: 'BREX', color: '#0052CC'},
    { value: 'purple', label: 'DISARM', color: '#5243AA' },
    { value: 'red', label: 'CRISPR', color: '#FF5630'},
    { value: 'orange', label: 'DISARMassociated', color: '#FF8B00' },
    { value: 'yellow', label: 'DND', color: '#FFC400' },
    { value: 'green', label: 'RM', color: '#36B37E' },
    { value: 'forest', label: 'TA', color: '#00875A' },
    { value: 'slate', label: 'WADJET', color: '#253858' },
    { value: 'silver', label: 'ZORYA', color: '#666666' },
    { value: 'softPurple', label: 'HACHIMAN', color: '#ea85ff'},
    { value: 'Black', label: 'LAMASSU', color: '#000000'},
    { value: 'militant', label: 'SEPTU', color: '#464a27'},
    { value: 'darkPurple', label: 'THOERIS', color: '#4a2626'},
    { value: 'pink', label: 'GABIJA', color: '#ff00ea'},
    { value: 'brightGreen', label: 'DRUANTIA', color: '#8fff02'},
];
