export const colourOptions = [
    { value: 'ocean', label: 'ABI', color: '#00B8D9'},
    { value: 'lightocean', label: 'ABI|PifA', color: '#75c4da'},
    { value: 'lighterocean', label: 'ABI|AbiE', color: '#95c1c9'},
    { value: 'darkocean', label: 'ABI|AbiJ', color: '#068aa1'},
    { value: 'darkerocean', label: 'ABI|AbiC', color: '#036678'},
    { value: 'darkestocean', label: 'ABI|PrrC', color: '#01424d'},
    { value: 'grayocean', label: 'ABI|AbiL', color: '#68abb6'},
    { value: 'lightgrayocean', label: 'ABI|AbiV', color: '#7dccdb'},
    { value: 'darkgrayocean', label: 'ABI|AbiH', color: '#3e575e'},
    { value: 'blue', label: 'BREX', color: '#0052CC'},
    { value: 'lighterblue', label: 'BREX|typeII', color: '#2b6bc8'},
    { value: 'lightblue', label: 'BREX|typeIII', color: '#698ec4'},
    { value: 'lightestblue', label: 'BREX|typeIV', color: '#899ebd'},
    { value: 'purple', label: 'DISARM', color: '#5243AA' },
    { value: 'darkpurple', label: 'DISARM|typeI', color: '#3d29ac' },
    { value: 'lightpurple', label: 'DISARM|typeII', color: '#695eab' },
    { value: 'red', label: 'CRISPR', color: '#FF5630'},
    { value: 'lighterred', label: 'CRISPR-CAS|typeI-C', color: '#f77559'},
    { value: 'lightred', label: 'CRISPR-CAS|typeI-E', color: '#ed9c89'},
    { value: 'lightestred', label: 'CRISPR-CAS|typeI-F', color: '#f9cac0'},
    { value: 'yellow', label: 'DND', color: '#FFC400' },
    { value: 'green', label: 'RM', color: '#36B37E' },
    {value: 'darkgreen',label:'RM|typeI', color:'#01ae65'},
    {value: 'lightgreen',label:'RM|typeII', color:'#79ae97'},
    {value: 'lightgreen2',label:'RM|typeIII', color:'#94b0a4'},
    { value: 'forest', label: 'TA', color: '#00875A' },
    { value: 'slate', label: 'WADJET', color: '#253858' },
    { value: 'darkslate', label: 'WADJET|typeI', color: '#002563' },
    { value: 'lightslate', label: 'WADJET|typeII', color: '#445369' },
    { value: 'lighterslate', label: 'WADJET|typeIII', color: '#5b75a7' },
    { value: 'silver', label: 'ZORYA', color: '#666666' },
    { value: 'darksilver', label: 'ZORYA|typeI', color: '#3b3b3b' },
    { value: 'lightsilver', label: 'ZORYA|typeII', color: '#959494' },
    { value: 'softPurple', label: 'HACHIMAN', color: '#ea85ff'},
    { value: 'Black', label: 'LAMASSU', color: '#000000'},
    { value: 'militant', label: 'SEPTU', color: '#464a27'},
    { value: 'darkPurple', label: 'THOERIS', color: '#4a2626'},
    { value: 'pink', label: 'GABIJA', color: '#ff00ea'},
    { value: 'brightGreen', label: 'DRUANTIA', color: '#8fff02'},
    { value: 'lighterbrightGreen', label: 'DRUANTIA|typeI', color: '#adf84f'},
    { value: 'lightbrightGreen', label: 'DRUANTIA|typeII', color: '#c9f494'},
    { value: 'darkbrightGreen', label: 'DRUANTIA|typeIII', color: '#6dc004'},
    { value: 'red',label: 'KIWA',color:'#ff0000'},
    {value: 'darkcyan', label:'PAGOS',color:'#013730'},
    {value: 'brightcyan', label:'SHEDU',color:'#00ffd5'},
    {value: 'orange', label:'Anti-CRISPR', color:'#FF8B00'},
    {value: 'lighterorange', label:'Anti-CRISPR IC', color:'#fca843'},
    {value: 'lightorange', label:'Anti-CRISPR IE', color:'#fbc482'},
    {value: 'darkorange', label:'Anti-CRISPR IF', color:'#9f5602'},
];
